# Generated by Django 4.2.16 on 2025-03-19 15:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
