# Generated by Django 4.2.16 on 2025-03-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_category_options'),
        ('checkout', '0005_order_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
    ]
