# Generated by Django 4.2.16 on 2025-03-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_orderlineitem_package'),
        ('checkout', '0010_fix_package_column'),
    ]

    operations = [
    ]
