# Generated by Django 4.2.16 on 2025-03-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='image',
            field=models.ImageField(default='tutors/noimage.png', upload_to='tutors/'),
        ),
    ]
