# Generated by Django 4.2.16 on 2025-03-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tutor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='image',
            field=models.ImageField(default='tutors/notutorimage.png', upload_to='tutors/'),
        ),
    ]
