# Generated by Django 4.2.16 on 2025-03-24 18:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tutor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='image',
            field=cloudinary.models.CloudinaryField(default='tutors/notutorimage.png', max_length=255, verbose_name='image'),
        ),
    ]
