# Generated by Django 4.2.16 on 2025-03-24 19:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_tutor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='notutor_bzsagz', max_length=255, null=True, verbose_name='image'),
        ),
    ]
